name: vtu_mobile
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Routing
  go_router: ^17.1.0

  # State management
  flutter_riverpod: ^3.2.1

  # Networking
  dio: ^5.7.0

  # Storage
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # UI helpers
  google_fonts: ^8.0.1
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  fluttertoast: ^9.0.0

  # Device / OS
  local_auth: ^3.0.0
  flutter_local_notifications: ^20.0.0
  connectivity_plus: ^7.0.0
  path_provider: ^2.1.1

  # Utilities
  intl: ^0.20.2
  url_launcher: ^6.2.2
  share_plus: ^12.0.1

  # PDF / Printing
  pdf: ^3.10.7
  printing: ^5.11.1

  # Payments
  # flutter_paystack: ^1.5.0
  provider: ^6.1.5+1
  permission_handler: ^12.0.1
  flutter_contacts: ^1.1.9+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Code generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
